apiVersion: v1
kind: Pod
metadata:
  name: frontend-two-pod
  namespace: lesson-bonus
  labels:
    app: frontend-two
spec:
  containers:
    - name: frontend-two
      image: local/frontend-two:1.0
      imagePullPolicy: IfNotPresent
      env:
        - name: BG_COLOR
          valueFrom:
            configMapKeyRef:
              name: frontend-two-config
              key: BG_COLOR
              optional: true
      ports:
        - containerPort: 80
